### PR TITLE
Bump package version.

### PR DESCRIPTION
**Pull request by dnadales**
I forgot to increase the version in the previous pull request. I have two questions:

1. What is the procedure to have this package updated in hackage?
2. Could you enable Travis for this repo, so that we can monitor the build status whenever somebody makes a pull request?

When upgrading `pipes-files` I won't bother you that much :) Thanks!

### CODE REVIEW

**Comment by dnadales** [comment]
Hi John, should I bump the version and look how to update this package in hackage myself? Although I don't know if that's possible since I'm not the hackage maitainer. Thanks.

**Comment by jwiegley** [comment]
What is your username on Hackage?  I'll add you as a maintainer to both packages there too.

**Comment by dnadales** [comment]
> What is your username on Hackage? I'll add you as a maintainer to both packages there too.

dnadales

In the future do you prefer me to merge the changes directly without making a pull request, or do you want to keep tabs on what's being changed in these libraries?

Thanks a lot.

**Comment by jwiegley** [comment]
You're now a maintainer on Hackage for both packages.

You don't need my approval through PR, go ahead and merge directly. You can be the full maintainer for as long as you have the interest to maintain these packages. I'm not using them currently, and don't want progress held back by me.

**Comment by dnadales** [comment]
Clear. Thanks a lot John.

**Pull request merged**
